# Scripts to generate Jade input tests


doit:		mul32-test

alu-bool-test:	alu-bool-test.py
		python $<

alu-test:	alu-test.py
		python $<

alu-shift-test:	alu-shift-test.py
		python $<

alu-arith-test:	alu-arith-test.py
		python $<

mux8-test:	mux8-test.py
		python $<

beta-pd-test:	beta-pc-test.py
		python $<

inc29-test:	inc29-test.py
		python $<

mul32-test:	mul32-test.py
		python $<

add32-test:	add32-test.py
		python $<

inc4-test:	inc4-test.py
		python $<


